name: test-conda-env
channels:
- conda-forge
- defaults

dependencies:
- python=3
- pip
- git
- conda-forge::numpy
- conda-forge::scipy
- sympy
- h5py
- pyopencl
- pocl
- fftw
- openmpi
- mpi4py
- mpi4py-fft
- clfft
- Cython

- pip:
    - loopy
    - git+https://gitlab.com/zachjweiner/gpyfft.git