name: test-conda-env
channels:
- conda-forge
dependencies:
- python=3
- pip
- git
- numpy
- scipy
- sympy
- h5py
- pyopencl
- pocl
- fftw
- openmpi
- mpi4py
- mpi4py-fft
- clfft
- loopy  # for dependencies, should be overwritten by pip

- pip:
    - git+https://github.com/inducer/loopy.git
    - git+https://github.com/zachjweiner/pycl-fft.git