name: pystella

channels:
- conda-forge

dependencies:
- python
- pip
- numpy
- scipy
- sympy
- h5py
- pyopencl
- pocl
- fftw
- mpi4py
- mpi4py-fft
- clfft

- pip:
    - git+https://github.com/inducer/loopy.git
    - git+https://github.com/zachjweiner/pycl-fft.git
    - pystella