name: pystella

channels:
- conda-forge
- defaults

dependencies:
- python=3
- pip
- conda-forge::numpy
- conda-forge::scipy
- sympy
- h5py
- pyopencl
- pocl
- fftw
- mpi4py
- mpi4py-fft
- clfft
- Cython
- pip:
    - git+https://github.com/inducer/loopy.git#egg=loo.py
    - git+https://gitlab.com/zachjweiner/gpyfft.git#egg=gpyfft
    - pystella