name: rtd310

channels:
- conda-forge
- defaults

dependencies:
- python=3.10
- pip
- numpy
- pyopencl
- islpy
- sphinx-copybutton
- pip:
  - "git+https://github.com/inducer/loopy.git#egg=loopy"
  - furo
