name: CI
on:
  push:
    branches: [ "**" ]
  pull_request:
    paths-ignore:
      - "doc/*.rst"
  schedule:
    - cron: "17 3 * * 0"

jobs:
  flake8:
    name: Flake8
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: "3.11"
      - name: Main Script
        run: |
          pip install flake8 flake8-quotes flake8-bugbear
          flake8

  pylint:
    name: Pylint
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: "3.11"
          environment-file: .test-conda-env-py3.yml
          miniforge-version: latest
          miniforge-variant: Mambaforge
          use-mamba: true
      - name: Conda info
        run: conda info
      - name: Conda list
        run: conda list
      - name: Main Script
        run: |
          pip install -e .
          pylint .

  pytest:
    name: Pytest
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: "3.11"
          environment-file: .test-conda-env-py3.yml
          miniforge-version: latest
      - name: Conda info
        run: conda info
      - name: Conda list
        run: conda list
      - name: Main Script
        run: |
          pip install -e .
          pytest -n 4 --ignore=test/test_examples.py
          pytest test/test_examples.py
          # FIXME: add doctest

  pytest-distributed:
    name: Pytest Distributed
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: "3.11"
          environment-file: .test-conda-env-py3.yml
          miniforge-version: latest
      - name: Conda info
        run: conda info
      - name: Conda list
        run: conda list
      - name: Main Script
        run: |
          pip install -e .
          mpirun --oversubscribe -np 4 pytest --proc_shape 2,2,1
          mpirun --oversubscribe -np 3 pytest test/test_decomp.py test/test_derivs.py --proc_shape 3,1,1
